name: Webhooks.Sender

on:
  push:
  pull_request:
    branches: [master]

env:
  DOTNET_VERSION: 6.0.201
  CONFIGURATION: Release

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Webhooks.Sender - Install dependencies
        run: dotnet restore "./web-api/Webhooks.Sender"

      - name: Webhooks.Sender - Build
        run: dotnet build "./web-api/Webhooks.Sender" --configuration $CONFIGURATION --no-restore

      - name: Webhooks.Sender.Tests - Install dependencies
        run: dotnet restore "./web-api/Webhooks.Sender.Tests"

      - name: Webhooks.Sender.Tests - Build
        run: dotnet build "./web-api/Webhooks.Sender.Tests" --configuration $CONFIGURATION --no-restore

      - name: Webhooks.Sender.Tests - Test
        run: dotnet test "./web-api/Webhooks.Sender.Tests" --configuration $CONFIGURATION --no-build --logger "console;verbosity=normal" /p:CollectCoverage=true /p:Threshold=13 /p:ThresholdType=line /p:CoverletOutput="./Coverage/coverage.json"
